Climber
cavineers/RobotCode2024 pull request #39
Opened 2024-02-05 21:54 UTC by ashley064

2024-02-06 00:43 UTC, Sam-Malta commented
Hey @ashley064 The code looks good, hopefully you were able to iron out that issue you were having. The build seems to be failing due to improperly named files. (leftClimber v LeftClimber) etc. Once that issue is resolved @BechtelLo25 can approve. Thanks

2024-02-06 00:44 UTC, Sam-Malta requested changes
Changes listed above^

2024-02-07 21:15 UTC, ashley064 commented
2/7/24 Update:
- I spoke to Zach before the meeting, and he will be renaming the files appropriately so that the build succeeds and the pull request can be accepted. I will confirm this during our meeting on 2/8/24.

2024-02-07 21:51 UTC, Sam-Malta approved these changes

2024-02-07 23:28 UTC, BechtelLo25 approved these changes

2024-02-07 23:32 UTC, merged